apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: lint
spec:
  workspaces:
    - name: output
  steps:
    - name: lint
      image: python:3.9-slim
      workingDir: $(workspaces.output.path)
      script: |
        #!/bin/bash
        pip install flake8
        flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 service --count --max-complexity=10 --max-line-length=127 --statistics